// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var $container, $hemi, $image;

    $hemi = $('#hemispheres');
    $container = $('.map-container', $hemi);
    $image = $('.map-image', $container);
    $image.load(function() {
      return $container.css('background-image', "url(" + ($image.attr('src')) + ")");
    });
    $('html').on('mousemove', function(e) {
      var x;

      x = e.screenX * 3;
      return $container.css('background-position', "" + x + "px 0");
    });
    return $hemi.click(function() {
      return $container.toggleClass('flipped');
    });
  });

}).call(this);
